name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.3+1
  universal_io: ^2.0.4
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.10.0
  flutter_credit_card: ^4.0.1
  smooth_page_indicator: ^1.1.0
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.10.5
  intl: ^0.19.0
  http: ^1.1.0              # Requêtes HTTP vers le backend
  local_auth: ^2.1.0        # Authentification biométrique (Touch ID, Face ID)
  flutter_secure_storage: ^8.0.0  
  provider: ^6.0.0          
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0
  carousel_slider: ^5.0.0
  permission_handler: ^11.4.0
  flutter_reactive_ble: ^5.4.0
  shimmer: ^3.0.0
  animate_do: ^4.2.0
  google_maps_flutter: ^2.12.0
  apple_maps_flutter: ^1.4.0
  flutter_map: ^8.1.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2 
  image_picker: ^1.1.2
  fl_chart: ^0.71.0
  flutter_stripe: ^11.5.0
  pinput: ^5.0.1
  flutter_animate: ^4.5.2
  nfc_manager: ^4.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/sp.png


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/sp.png
    - assets/images/google_icon.png
    - assets/images/apple_icon.png
    - assets/images/email_icon.png
    - assets/images/power.png
    - assets/images/station.png
    - assets/images/monoprix.png
    - assets/images/face-id.png
    - lib/l10n/app_en.arb
    - lib/l10n/app_fr.arb

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


  