name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.3+1
  universal_io: ^2.0.4
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.10.0
  http: ^1.1.0              # Requêtes HTTP vers le backend
  local_auth: ^2.1.0        # Authentification biométrique (Touch ID, Face ID)
  geolocator: ^10.0.0       # Géolocalisation
  flutter_secure_storage: ^8.0.0  # Stockage sécurisé (token, PIN)
  provider: ^6.0.0          # Gestion d'état

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/sp.png


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/sp.png
    - assets/images/google_icon.png
    - assets/images/apple_icon.png
    - assets/images/email_icon.png
    - assets/images/power.png
    - assets/images/station.png
    - assets/images/monoprix.png
    - assets/images/unnamed.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700


  